apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-argo-workflows-dev
images:
  - name: busybox
    newName: busybox
    newTag: latest
resources:
  - ./templates/