apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-argo-workflows-dev
configurations:
- kustomconfig.yaml
resources:
  - ./templates/testworkflowtemplate.yaml
images:
  - name: busybox
    newName: busybox
    newTag: ''