apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-argo-workflows-dev
resources:
  - ./templates/testworkflowtemplate.yaml
images:
  - name: gbusybox
    newName: busybox
    newTag: latest