apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-test-image
spec:
  entrypoint: print-message
  templates:
    - name: print-message
      inputs:
        parameters:
          - name: message
      script:
        image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        command: [sh]
        source: |
          echo "{{inputs.parameters.message}}"
