apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-print-message
spec:
  entrypoint: print-message
  templates:
    - name: print-message
      inputs:
        parameters:
          - name: message
      script:
        image: busybox:1.36.0
        command: [sh]
        source: |
          echo "{{inputs.parameters.message}}"
